cmd/talisman/run_px_upgrade.sh, pkg/cluster/px/px.go
=> Return error if current DaemonSet is of type docker

Gopkg.lock, pkg/cluster/px/px.go, vendor/github.com/go-openapi/spec/expander.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
=> Don't start upgrade if Portworx is not ready on any given node

pkg/cluster/px/px.go
=> mount talisman service account to docker puller daemonset

Gopkg.lock, pkg/cluster/px/px.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
=> delete all px components in the cluster

Gopkg.lock, cmd/talisman/talisman.go, pkg/cluster/px/px.go, pkg/k8sutils/k8sutils.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
**Which issue(s) this PR fixes** 
Closes #39
=> Handle standalone pods

Dockerfile.talisman, Makefile
=> Use RHEL atomic as base for talisman

pkg/cluster/px/px.go
=> delete node wiper daemonset if successfull

pkg/cluster/px/px.go
=> Stop and delete PX components before invoking per node wipe

pkg/cluster/px/px.go
=> Don't run docker puller on nodes where px doesn't run

pkg/cluster/px/px.go
=> Check for PX upgrade to 1.4

Dockerfile.build, Makefile, pkg/cluster/px/px.go
1) Add new oci monitor image for openshift in search regex 
2) fix host mount for node wiper
This fixes PWX-5336
=> PX node wiper fixes for Openshift

pkg/cluster/px/px.go
This fixes https://portworx.atlassian.net/browse/PWX-5411
=> Run docker puller as privileged container

pkg/cluster/px/px.go
This fixes https://portworx.atlassian.net/browse/PWX-5410
=> Delete PX PVC controller during node wipe

Gopkg.lock, pkg/cluster/px/px.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
- delete objects needed for k8s secrets
- delete the cluster wide secret
Signed-off-by: Piyush Nimbalkar <piyush@portworx.com>
Closes #
=> Delete Lighthouse objects and its config

pkg/cluster/px/px.go
=> Drain apps for 1.3.4 also

pkg/cluster/px/px.go
=> Delete the daemonset unconditionally after running it

examples/px-cluster-comprehensive.yaml, examples/px-cluster.yaml, examples/px-crd.yaml, pkg/apis/portworx/register.go, pkg/apis/portworx/v1beta1/doc.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/fake/fake_cluster.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/fake/fake_volumeplacementstrategy.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/portworx_client.go, pkg/client/informers/externalversions/generic.go
=> Use portworx.io for CRD group

pkg/cluster/px/px.go
=> Use stripped cluster name for px config map names

cmd/px-node-wiper/px-node-wiper.sh, pkg/cluster/px/px.go
=> Use local systemctl commands in wiper

pkg/cluster/px/px.go
Syncing node-get-put-list-role cluster role from https://install.portworx.com for upgrade
Closes #
=> sync cluster role

pkg/cluster/px/px.go
**What this PR does / why we need it**: The daemonset detection code was checking image names which didn't work for GCP marketplace as it uses custom image names.
The PR simplifies the logic and removes parsing of image names. This was present when we had customers installing PX using docker containers directly (no oci-monitor). All customers use oci-monitor now so that logic can be removed.
The PR will now also delete PX components from all namespaces.
=> Fix daemonset detection for GCP marketplace

pkg/cluster/px/px.go
=> Delete bootstrap and cloud drive configmap in kube-system namespace

pkg/cluster/px/px.go
Signed-off-by: Thiago Gonzaga <thi_gonzaga@yahoo.com.br>
**What this PR does / why we need it**: This PR adds purpose to params `-pxtag`, `-pximage` and `-dockerregsecret` allowing the user to specify px image to upgrade and docker registry credentials through k8s secrets
=> fix talisman to use pxtag and pximage params and docker secrets

pkg/cluster/px/px.go
Needed after https://github.com/portworx/porx/pull/3765
Closes #
=> Add watch and update permissions for pods

cmd/px-node-wiper/Dockerfile, pkg/cluster/px/px.go
These mounts were needed to the wiper to work on IKS.
Closes #
=> PWX-9022 Add missing mounts to the node wiper pods

pkg/cluster/px/px.go
- Update the node wiper image tag to 2.0.3.6
Signed-off-by: Aditya Dani <aditya@portworx.com>
Closes #
=> Provide the "-r" argument to the node wiper image.

pkg/cluster/px/px.go
=> Ignore version check error for application drain during upgrade

pkg/cluster/px/px.go
Signed-off-by: Grant Griffiths <grant@portworx.com>
=> Cleanup px-csi-ext deployment

pkg/cluster/px/px.go
=> PWX-9739 Delete OSB secert

cmd/px-node-wiper/Dockerfile, cmd/px-node-wiper/px-node-wiper.sh
=> PWX-9740 remove chattr attribute from config.json

pkg/cluster/px/px.go
=> PWX-9991 enable host network for api daemonset

pkg/cluster/px/px.go
=> PWX-10061 lookup user's custom service ports during upgrade

pkg/cluster/px/px.go
The upgrade checks for the PX_IMAGE env variable was causing other sideeffects where the upgrade process was incorrectly detecting the generation. 
Closes #
=> PWX-10109 Remove support for PX_IMAGE upgrade

cmd/talisman/talisman.go, pkg/cluster/px/px.go
Signed-off-by: Maksym Borodin <maksym@portworx.com>
Because we need to increase timeout during upgrade in the test from older 1.x to 2.x PX version.
Closes #PWX-10108
=> PTX-1940 Added upgrade timeout per node parameter

pkg/cluster/px/px.go
=> PWX-10258 use user's custom ports for API service

cmd/px-node-wiper/px-node-wiper.sh
* doing `systemctl daemon-reload` after service-files removed
* code-alignment cleanup
Signed-off-by: Zoran Rajic <zox@portworx.com>
See PWX-10905
Closes #PWX-10905
you might want to review DIFF with "whitespace changes ignored"
=> PWX-10905: adding systemd refresh into px-wipe

pkg/cluster/px/px.go
=> PWX-12497 update px rbac permissions

pkg/cluster/px/px.go
=> PWX-15595 Add missing storage class permissions

pkg/cluster/px/px.go
Signed-off-by: Harsh Desai <hadesai@purestorage.com>
Closes #
=> PWX-20866 Delete pure cloud drive config map

pkg/cluster/px/px.go, pkg/cluster/px/px_test.go, vendor/github.com/portworx/sched-ops/k8s/admissionregistration/admissionregistration.go, vendor/github.com/portworx/sched-ops/k8s/admissionregistration/mutationwebhooks.go, vendor/github.com/portworx/sched-ops/k8s/admissionregistration/mutationwebhooks_v1beta1.go, vendor/modules.txt
Signed-off-by: Luke Pitstick <lpitstick@purestorage.com>
Cleanup stork webhook so we don't timeout trying to call a disabled webhook
Closes #PWX-23449
=> PWX-23449 cleanup stork webhook on wipe

Makefile
This is for testing purpose only. Please ignore this PR.
=> revert: fake commit to generate SCM Change event

.travis.yml, Makefile, cmd/px-node-wiper/Dockerfile, pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go, pkg/cluster/px/px_test.go
update golang and base container for node-wiper.
Closes #
PWX-33740
WebSrv PR:  https://github.com/portworx/px-installer/pull/1901
Testing Note:
Scans show no criticals but we have some highs.
Talisman:  https://aetos.pwx.purestorage.com/security/PXE/HOSE/2023-09-26-06-50-00-237175
Node-Wiper:   https://aetos.pwx.purestorage.com/security/PXE/HOSE/2023-09-25-23-34-12-512529.
=> PWX-33740 - updates for vuln fixes

pkg/apis/portworx/v1beta2/types.go, pkg/apis/portworx/v1beta2/zz_generated.deepcopy.go
=> PWX-27968: Add NamespaceSelector parameter to VPS spec
