Gopkg.lock, pkg/cluster/px/px.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
From newer Portworx release, if customers plan to use Kubernetes secrets, they should have permissions to the portworx namespace. This namespace will have the cluster secrets and cloud credentials.
Closes #
=> Add extra permissions needed to access k8s secrets

cmd/px-node-wiper/Dockerfile, cmd/talisman/talisman.go, pkg/cluster/px/px.go
- Also updating wiper image to be based on latest 1.5.1
**What this PR does / why we need it**: If people run PX wipe and daemonset specs are not applied, the current error message is not clear. 
```
time="2018-09-05T16:15:01Z" level=fatal msg="failed to instantiate PX cluster provider. err: services \"portworx-service\" not found"
```
Now it will display something like
```
time="2018-10-10T21:28:08Z" level=info msg="Attempting to parse kvdb info from Portworx daemonset"
time="2018-10-10T21:28:08Z" level=fatal msg="Failed to delete PX cluster. err: Failed to parse PX config from Daemonset for deleting PX due to err: Portworx daemonset not found on the cluster. Ensure you have Portworx specs applied in the cluster before issuing this …
```
=> Clarify message when wipe is issued and PX specs are not applied

Makefile, cmd/px-node-wiper/px-node-wiper.sh, pkg/cluster/px/px.go
**What this PR does / why we need it**:  docker.sock, /etc/pwx and /opt/pwx mounts are different for PKS. The wipe and upgrade scripts need to detect PKS and use these.
Closes #
=> Auto-detect PKS and change mount points accordingly

pkg/apis/portworx/v1beta1/types.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/fake/fake_portworx_client.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/fake/fake_volumeplacementstrategy.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/portworx_client.go, pkg/client/clientset/versioned/typed/portworx/v1beta1/volumeplacementstrategy.go, pkg/client/informers/externalversions/portworx/v1beta1/interface.go, pkg/client/informers/externalversions/portworx/v1beta1/volumeplacementstrategy.go, pkg/client/listers/portworx/v1beta1/expansion_generated.go, pkg/client/listers/portworx/v1beta1/volumeplacementstrategy.go
**What this PR does / why we need it**: volume placement strategies  will be referenced in storage classes and hence should not be scoped by namespaces.
Closes #
=> volume placement strategies should be cluster scoped

Makefile, pkg/apis/portworx/v1beta1/types.go
Can't use existing osd types since they are ints and users will specify strings in the CRD spec
Closes #
=> volume placement crd change to fix enforcement and affinity type

pkg/cluster/px/px.go
* talisman will insert permissions for `configmaps`, so that the "internal KVDB" px-custers can get get upgraded
Signed-off-by: @zoxpx
PWX-7451: px-1.7 to 2.0 upgrade fails if px using internal KVDB
PWX-7451
=> PWX-7451: Fixing px-upgrades with Kvdb

pkg/cluster/px/px.go
**What this PR does / why we need it**: When install, Portworx creates a namespace called "portworx". On wipe, we need to delete this.
Closes #
=> Delete portworx namespace on wipe

cmd/px-node-wiper/Dockerfile, cmd/px-node-wiper/px-node-wiper.sh, cmd/talisman/talisman.go, pkg/cluster/px/px.go
Running systemctl commands directly in the default debian AMIs used in KOPS fails. It returns the "Failed to connect to bus: No data available" error.
This change now does both approaches (nsenter and systemctl). Tested on KOPS debian AMI and coreos machines.
=> Fix node wiper for kops debian AMIs

pkg/cluster/px/px.go
**What this PR does / why we need it**: talisman wipe now also deletes PX api daemonset and service
Closes #
=> Delete portworx-api daemonset and service

pkg/cluster/px/px.go, vendor/github.com/portworx/sched-ops/k8s/k8s.go
**What this PR does / why we need it**: On certain installations like GCP marketplace, end users could have installed PX specs on a custom namespace. The delete and upgrade operations should detect this.
=> talisman to detect the installed namespace

pkg/cluster/px/px.go
Syncing px cluster role permisions from https://edge-install.portworx.com
Closes #
=> Update the Portworx cluster role permissions

cmd/px-node-wiper/Dockerfile, pkg/cluster/px/px.go
This fixes a nil panic in pxctl 2.0
https://github.com/portworx/porx/pull/3471/commits/c146afb423eb3c0a6a1bde86802700611f891a29
Closes #
=> Bump node wiper to use 2.1.1 pxctl

pkg/cluster/px/px.go
Signed-off-by: Jose Rivera <jose@portworx.com>
HostPID: true to allow nsenter runs to execute host commands
Will be used during node-wipe.
=> PWX-9687: Add 'HostPID: true' to node-wiper spec.

pkg/cluster/px/px.go
**What this PR does / why we need it**: This PR parses the affinity rules from the PX daemonset and uses the same rules to create the node wiper and the portworx API daemonset.
Closes #
=> add PX daemonset affinity to the api and wiper daemonset

cmd/px-node-wiper/Dockerfile, pkg/cluster/px/px.go
Delete the px-essential secret as a part of cluster wipe
Closes #
=> Delete px-essential secret during wipe

pkg/cluster/px/px.go
Signed-off-by: Jose Rivera <jose@portworx.com>
Add /var/cores for alerts cleanup.
Closes #: PWX-12134
=> PWX-12134: Add /var/cores to volume mounts of px-node-wiper

pkg/cluster/px/px.go
This is needed by pxctl sv node-wipe to be able to function after the pxctl change after https://portworx.atlassian.net/browse/PWX-18104
px-wipe script on https://install.portworx.com/px-wipe fails, because `talisman` runs `px-node-wiper` calls `pxctl sv node-wipe`. This fails because pxctl has been changed to use local Unix DS at `/var/lib/osd/driver/`
PWX-18849
=> PWX-18849: px-node-wiper needs to mount /var/lib/osd/driver

.travis.yml, pkg/cluster/px/px.go, pkg/k8sutils/k8sutils.go
* add support for authenticated EtcD
* should work with "verbatim" user/passwd, as well as Secret-Key references via env. variables
Signed-off-by: Zoran Rajic <zox@portworx.com>
Cluster-wipe via `px-wipe` bootstrap would not delete content from the external EtcD, if EtcD was using username/password AuthN.
This adds a fix to the Talisman, so that the proper EtcD username/password is extracted -- be it "verbatim" value, or reference to K8s secret via the env-variables.
Closes # PWX-19250
=> PWX-19250: fix etcd authN

cmd/px-node-wiper/Dockerfile, cmd/px-node-wiper/px-node-wiper.sh
Portworx stop was not succeeding using nsenter and from systemd run inside the container.   So add another attempt  to stop portworx using the dbus socket if it exist.
Closes #
PWX-22998
=> PWX-22998: CVE base container update

Dockerfile.talisman
Signed-off-by: Jose Rivera <jose@portworx.com>
Update the Talisman base container to use ubi8-minimal to pick up security vulnerability fixes.
Closes #
PWX-23224
=> PWX-23224: Update base container to use ubi8-minimal for security fixes.

cmd/px-node-wiper/px-node-wiper.sh, cmd/talisman/talisman.go, pkg/cluster/px/px.go, pkg/k8sutils/logutil.go
Talisman changes:
* adding `--log <logfile>` also `--debug` and `--trace` options
- DEBUG-level traces Kubernetes calls and errors
- TRACE-level adds Kubernetes API output  (REST-results in JSON format)
* adding /var/cores mount
* copied DebugDumpObjectJS/TraceDumpObjectJS from porx, used to dump complex API objects
Node-wipe changes:
* increased `InitialDelaySeconds` from 30 to 120 seconds
* node-wiper stores "full trace" to /var/cores/px-node-wipe
- always appends, will no longer maintain separate log-files
* logging activates only when `--debug` flag was passed  (passed from talisman)
* removed `sleep_forever()` -- using `sleep 1800` instead  (that's 30 minutes sleep)
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
Talisman was never …
=> PWX-27003-pt1: Improved logging for Talisman / Node-wiper

Makefile
- This PR enables the build system to use DOCK_BUILD_CNT i.e  go docker build container. This improvement is required as we are moving away form travis and adopting Jenkins builds.
- Makefile updates with `docker build --pull` command to enable always pull the latest base feature while building. It's usually a good practice to use it to get upstream security fixes incorporated as soon as possible (instead of using stale, potentially vulnerable images)
=> update Makefile to use DOCK_BUILD_CNT

Dockerfile.build, Dockerfile.talisman, Makefile, cmd/px-node-wiper/Dockerfile
* talisman's base-container to UBI9
* upgraded golang to 1.21.x
* upgrade node-wiper to latest px-lib base container
Fixing versions of the base-container, and the golang
Closes # PWX-35213
testing notes:
* wiping cluster worked OK
```
The operation will delete Portworx components and metadata from the cluster. The operation is irreversible and will lead to DATA LOSS. Do you want to continue? [y/N]:y
Parsed kubernetes versions are 1.28.4 (Server) and 1.26.4 (Client)
serviceaccount/talisman-account created
clusterrolebinding.rbac.authorization.k8s.io/talisman-role-binding created
job.batch/talisman created
Talisman job for wiping Portworx started. Monitor logs using: …
```
=> PWX-35213: upgrade versions

pkg/apis/portworx/v1beta2/types.go, pkg/apis/portworx/v1beta2/zz_generated.deepcopy.go
NamespaceSelector is no longer needed, thus reverting this change.
Closes #
=> Revert PWX-27968: Add NamespaceSelector parameter to VPS spec (#136)
